name: Configure Organization Custom Properties
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  id-token: write

jobs:
  update-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
          ref: ${{ github.ref_name }}

      - name: Set Organization Custom Properties
        id: set_custom_properties
        uses: PandasWhoCode/configure-custom-properties@6e40078d7ba5e357ecdd240a3533625395d3e0ba # v1.0.0
        with:
          token: ${{ secrets.GH_CUSTOM_PROPS_TOKEN }}
          config-file: ${{ github.workspace }}/properties_schema.json
