name: Read all custom properties for all repos in an organization

description: Read all custom properties for all repos in an organization

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: "0"
          ref: ${{ github.ref_name }}
